# Base operating-system hardening that is not specific to mail.
{
  config,
  lib,
  settings,
  ...
}:
{
  time.timeZone = settings.timeZone;

  # --- SSH: keys only, modern algorithms, root only via key -----------------
  services.openssh = {
    enable = true;
    # Opened below, possibly only for settings.sshAllowedCidrs.
    openFirewall = false;
    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "prohibit-password";
      X11Forwarding = false;
      AllowAgentForwarding = false;
      # Only `ssh -L port:/unix/socket`, used to reach the Rspamd web UI.
      AllowStreamLocalForwarding = "local";
      AllowTcpForwarding = false;
      MaxAuthTries = 3;
      LoginGraceTime = 20;
      ClientAliveInterval = 300;
      ClientAliveCountMax = 2;
      KexAlgorithms = [
        "mlkem768x25519-sha256"
        "sntrup761x25519-sha512"
        "sntrup761x25519-sha512@openssh.com"
        "curve25519-sha256"
        "curve25519-sha256@libssh.org"
      ];
      Ciphers = [
        "chacha20-poly1305@openssh.com"
        "aes256-gcm@openssh.com"
        "aes128-gcm@openssh.com"
      ];
      Macs = [
        "hmac-sha2-512-etm@openssh.com"
        "hmac-sha2-256-etm@openssh.com"
      ];
    };
    # Only an Ed25519 host key, pre-generated by `just init` so that its
    # fingerprint is pinned in known_hosts before the first connection.
    hostKeys = [
      {
        path = "/etc/ssh/ssh_host_ed25519_key";
        type = "ed25519";
      }
    ];
  };

  users.mutableUsers = false;
  users.users.root.openssh.authorizedKeys.keys = settings.sshKeys;
  # No password login for root at all (console access goes through the
  # DigitalOcean recovery console, which uses SSH keys or a reset).
  users.users.root.hashedPassword = "!";

  # --- Brute-force protection -------------------------------------------------
  services.fail2ban = {
    enable = true;
    maxretry = 5;
    bantime = "1h";
    bantime-increment = {
      enable = true;
      maxtime = "1w";
      overalljails = true;
    };
    # Only authentication failures are banned. Port 25 protocol errors are
    # deliberately not: that would eventually ban the outbound IPs of large
    # providers (Gmail, Outlook) and delay legitimate mail. Rspamd handles
    # unwanted inbound mail instead.
    jails = {
      postfix-sasl.settings = {
        filter = "postfix[mode=auth]";
        port = "submissions";
        maxretry = 3;
      };
      # fail2ban's bundled `dovecot` filter matches neither the NixOS unit
      # name nor Dovecot 2.4's log format; see fail2ban/dovecot-imap.nix.
      dovecot-imap = {
        filter = import ./fail2ban/dovecot-imap.nix;
        settings = {
          port = "imaps";
          maxretry = 3;
          backend = "systemd";
        };
      };
    };
  };

  # --- Firewall -------------------------------------------------------------
  # Only the ports opened by the mail and web modules (and SSH) are
  # reachable. Most providers here have no usable cloud firewall, so this
  # host firewall is the one that counts.
  networking.firewall =
    let
      cidrs = settings.sshAllowedCidrs;
      v4 = lib.filter (c: !lib.hasInfix ":" c) cidrs;
      v6 = lib.filter (c: lib.hasInfix ":" c) cidrs;
      everyone = lib.elem "0.0.0.0/0" v4 && lib.elem "::/0" v6;
      set = l: "{ ${lib.concatStringsSep ", " l} }";
    in
    {
      enable = true;
      allowPing = true;
      logRefusedConnections = false;
      allowedTCPPorts = lib.mkIf everyone [ 22 ];
      extraInputRules = lib.mkIf (!everyone) (
        lib.optionalString (v4 != [ ]) "ip saddr ${set v4} tcp dport 22 accept\n"
        + lib.optionalString (v6 != [ ]) "ip6 saddr ${set v6} tcp dport 22 accept\n"
      );
    };
  networking.nftables.enable = true;

  # --- Kernel ---------------------------------------------------------------
  boot.kernel.sysctl = {
    "kernel.kptr_restrict" = 2;
    "kernel.dmesg_restrict" = 1;
    "kernel.unprivileged_bpf_disabled" = 1;
    "kernel.yama.ptrace_scope" = 1;
    "kernel.kexec_load_disabled" = 1;
    "kernel.sysrq" = 0;
    "net.core.bpf_jit_harden" = 2;
    "fs.protected_fifos" = 2;
    "fs.protected_regular" = 2;
    "fs.suid_dumpable" = 0;

    "net.ipv4.tcp_syncookies" = 1;
    "net.ipv4.tcp_rfc1337" = 1;
    "net.ipv4.conf.all.rp_filter" = 1;
    "net.ipv4.conf.default.rp_filter" = 1;
    "net.ipv4.conf.all.accept_redirects" = 0;
    "net.ipv4.conf.default.accept_redirects" = 0;
    "net.ipv4.conf.all.secure_redirects" = 0;
    "net.ipv4.conf.default.secure_redirects" = 0;
    "net.ipv4.conf.all.send_redirects" = 0;
    "net.ipv4.conf.default.send_redirects" = 0;
    "net.ipv4.conf.all.accept_source_route" = 0;
    "net.ipv4.conf.default.accept_source_route" = 0;
    "net.ipv4.conf.all.log_martians" = 1;
    "net.ipv4.icmp_echo_ignore_broadcasts" = 1;
    "net.ipv6.conf.all.accept_redirects" = 0;
    "net.ipv6.conf.default.accept_redirects" = 0;
    "net.ipv6.conf.all.accept_source_route" = 0;
    "net.ipv6.conf.default.accept_source_route" = 0;
  };
  boot.blacklistedKernelModules = [
    "dccp"
    "sctp"
    "rds"
    "tipc"
    "firewire-core"
    "thunderbolt"
  ];
  boot.tmp.cleanOnBoot = true;

  # --- Misc -----------------------------------------------------------------
  security.sudo.enable = false;
  nix.settings = {
    allowed-users = [ "root" ];
    experimental-features = [
      "nix-command"
      "flakes"
    ];
    auto-optimise-store = true;
  };
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
  services.journald.extraConfig = ''
    SystemMaxUse=500M
    MaxRetentionSec=3month
  '';
  documentation.enable = false;

  # Keep the system patched. Only active when settings.autoUpgrade.enable is
  # set and the flake is reachable from the server.
  system.autoUpgrade = lib.mkIf settings.autoUpgrade.enable {
    enable = true;
    flake = settings.autoUpgrade.flake;
    dates = "04:00";
    randomizedDelaySec = "45min";
    allowReboot = true;
    rebootWindow = {
      lower = "03:00";
      upper = "06:00";
    };
  };

  assertions = [
    {
      assertion = settings.sshKeys != [ ];
      message = "settings.nix: add at least one SSH public key to `sshKeys`, or you will be locked out.";
    }
  ];

  system.stateVersion = "26.05";
}
