#!/usr/bin/env bash
# One-time setup of the encryption keys for this repository:
#   1. an age key for you (the admin), if you don't have one yet
#   2. the server's SSH host key, generated here so its fingerprint is known
#      before the server exists (no trust-on-first-use) and so secrets can be
#      encrypted to the server before it is installed
#   3. .sops.yaml and an empty secrets/secrets.yaml
#   4. DKIM keys for every domain in settings.nix
source "$(dirname "$0")/lib.sh"
cd "$ROOT"

[[ ! -f "$SECRETS" ]] || die "secrets/secrets.yaml already exists; refusing to overwrite it."

key_file="$(age_key_file)"
if [[ ! -f "$key_file" ]]; then
  info "Creating your admin age key at $key_file"
  mkdir -p "$(dirname "$key_file")"
  (umask 077 && age-keygen -o "$key_file")
  echo "    Back this file up somewhere safe (e.g. a password manager)."
  echo "    Without it you cannot decrypt the secrets in this repository."
fi
admin_age="$(age-keygen -y "$key_file" | head -n1)"
info "Admin age recipient: $admin_age"

mkdir -p secrets
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

info "Generating the server's SSH host key"
ssh-keygen -q -t ed25519 -N "" -C "root@$(fqdn)" -f "$tmp/ssh_host_ed25519_key"
cp "$tmp/ssh_host_ed25519_key.pub" "$HOST_KEY_PUB"
host_age="$(ssh-to-age < "$HOST_KEY_PUB")"
info "Server age recipient: $host_age"

cat > .sops.yaml <<EOF
# Generated by 'just init'. Each secret is encrypted to the keys listed here.
keys:
  - &admin $admin_age
  - &server $host_age
creation_rules:
  # Runtime secrets: readable by you and by the server.
  - path_regex: ^secrets/secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *server
  # The server's own private SSH key: only you can read it.
  - path_regex: ^secrets/ssh_host_ed25519_key\.enc$
    key_groups:
      - age:
          - *admin
EOF

sops encrypt --input-type binary --output-type binary \
  --filename-override secrets/ssh_host_ed25519_key.enc \
  "$tmp/ssh_host_ed25519_key" > "$HOST_KEY_ENC"

printf 'mailboxes: {}\ndkim: {}\n' > "$tmp/secrets.yaml"
sops encrypt --filename-override secrets/secrets.yaml "$tmp/secrets.yaml" > "$SECRETS"

for domain in $(setting domains | jq -r '.[]'); do
  "$ROOT/scripts/add-domain.sh" "$domain"
done

cat <<EOF

Keep this repository PRIVATE: settings.nix lists every mailbox, and the
encrypted secrets stay in git history forever (see docs/security.md).

Done. Next steps:
  1. Set a password for each mailbox:   just passwd <address>
  2. Commit .sops.yaml, secrets/ and dkim/ (everything there is encrypted or public).
  3. Create the infrastructure:          just apply
EOF
